export default function getMessages(version) {
  return {
    extensionName: "Scratch Addons",
    messaging: "Messaging",
    games: "Games",
    openInNewTab: "Open in new browser tab",
    changelog: "View changelog",
    recommended: "Recommended",
    beta: "Beta",
    forums: "Forums",
    forEditor: "For editor",
    forWebsite: "For website",
    confirmPreset: "Are you sure you want to load this preset?",
    confirmReset: "Are you sure you want to reset this addon to default settings?",
    settingsTitle: "Settings - Scratch Addons",
    settings: "Settings",
    all: "All",
    editorFeatures: "Scratch Editor Features",
    websiteFeatures: "Scratch Website Features",
    themes: "Themes",
    theme: "Theme:",
    credits: "Credits",
    review: "Review",
    feedback: "Send Feedback",
    moreSettings: "More Settings",
    filter: "Filter:",
    resetToDefault: "Reset to default settings",
    creditTo: "Credit to:",
    viewLicenses: "View library licenses",
    reset: "Reset",
    presets: "Presets",
    scratchAddonsTheme: "Scratch Addons theme",
    scratchAddonsThemeDescription: "This allows you to switch between light and dark themes for this settings page, and the extension's popup.",
    light: "Light",
    dark: "Dark",
    licensesTitle: "Licenses - Scratch Addons",
    licenses: "Licenses",
    licensesForLibrary: "Licenses for library $1",
    libraryCredits: "View licenses of used libraries",
    recommendedTooltip: "This is recommended by Scratch Addons. Try it out!",
    betaTooltip: "Keep in mind that this addon might have bugs.",
    forumsTooltip: "This addon applies to Scratch's Discussion Forums.",
  }
}
